# Generated by Django 5.1.4 on 2024-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10, unique=True)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=64)),
                ('Pfp', models.ImageField(upload_to='user/')),
            ],
        ),
    ]
