# Generated by Django 5.1.4 on 2024-12-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazariApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=250)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pictures', models.ImageField(upload_to='product/')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazariApp.user')),
            ],
        ),
    ]
