# Generated by Django 5.1.4 on 2025-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazariApp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Pictures',
            new_name='Picture_main',
        ),
        migrations.AddField(
            model_name='product',
            name='Picture_second',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Picture_third',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
