# Generated by Django 5.1.4 on 2025-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazariApp', '0003_rename_pictures_product_picture_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('deco', 'Deco'), ('clothing', 'Clothing'), ('antiques', 'Antiques')], default=None, max_length=20, null=True),
        ),
    ]
