# Generated by Django 5.1.4 on 2025-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazariApp', '0007_historypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypayment',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
